# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ygg < Formula
  desc "Simple CLI for managing git worktrees"
  homepage "https://github.com/joch/ygg"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joch/ygg/releases/download/v0.2.0/ygg_0.2.0_Darwin_x86_64.tar.gz"
      sha256 "9db4487cacbb61e6476e7c1877d0cad493482b23cf3994c198fbef3149a49e39"

      define_method(:install) do
        bin.install "ygg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joch/ygg/releases/download/v0.2.0/ygg_0.2.0_Darwin_arm64.tar.gz"
      sha256 "45fed71684f2713dd5707cf9f623e81c12427785392f6d6f94bada337a35e37d"

      define_method(:install) do
        bin.install "ygg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joch/ygg/releases/download/v0.2.0/ygg_0.2.0_Linux_x86_64.tar.gz"
      sha256 "d1a5d1c6df4bade4c96b3e91ba50e323e2f14939ea9dea302951755e023ebf6b"
      define_method(:install) do
        bin.install "ygg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joch/ygg/releases/download/v0.2.0/ygg_0.2.0_Linux_arm64.tar.gz"
      sha256 "4a91635e33b504a361048428ea50d443f0f18dcbaff83486e8da878ddd8624a2"
      define_method(:install) do
        bin.install "ygg"
      end
    end
  end

  test do
    system "#{bin}/ygg", "--version"
  end
end
