# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ygg < Formula
  desc "Simple CLI for managing git worktrees"
  homepage "https://github.com/joch/ygg"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joch/ygg/releases/download/v0.3.1/ygg_0.3.1_Darwin_x86_64.tar.gz"
      sha256 "879a870735181f6f8593484c517613c661be39f86ad8ac7c0b0ef5eea6be00bc"

      define_method(:install) do
        bin.install "ygg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joch/ygg/releases/download/v0.3.1/ygg_0.3.1_Darwin_arm64.tar.gz"
      sha256 "0aa2a2909011fabac8e11f049c30abb882afc3eceabe82f53ad976fb631835c5"

      define_method(:install) do
        bin.install "ygg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joch/ygg/releases/download/v0.3.1/ygg_0.3.1_Linux_x86_64.tar.gz"
      sha256 "6a21e0fda5ac6b1ae36b501f3b12a35f3b6edff53bb562765e1bfdc4b313c1b5"
      define_method(:install) do
        bin.install "ygg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joch/ygg/releases/download/v0.3.1/ygg_0.3.1_Linux_arm64.tar.gz"
      sha256 "a59cadd31b1a4574e7944e4253b4556d96f2066337ef81a952ec57b82be6e3bb"
      define_method(:install) do
        bin.install "ygg"
      end
    end
  end

  test do
    system "#{bin}/ygg", "--version"
  end
end
