# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ygg < Formula
  desc "Simple CLI for managing git worktrees"
  homepage "https://github.com/joch/ygg"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joch/ygg/releases/download/v0.1.0/ygg_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "2f6188d5b01002764e59f737d29135895dcf78d1e9cc7744521310921ffcf4a7"

      def install
        bin.install "ygg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joch/ygg/releases/download/v0.1.0/ygg_0.1.0_Darwin_arm64.tar.gz"
      sha256 "d6b7924eb24c509fc050200d4932ae3def171f0a02bcddfd2b651533c4c6e7a4"

      def install
        bin.install "ygg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joch/ygg/releases/download/v0.1.0/ygg_0.1.0_Linux_x86_64.tar.gz"
      sha256 "2896b6c26de4d92e3ef1165c3098f9063dc1511cb6835a116835750efbe256ce"
      def install
        bin.install "ygg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joch/ygg/releases/download/v0.1.0/ygg_0.1.0_Linux_arm64.tar.gz"
      sha256 "44a1a9e5a4ba93eed8c07316d28243e8ad2888a796493527213ada3616445236"
      def install
        bin.install "ygg"
      end
    end
  end

  test do
    system "#{bin}/ygg", "--version"
  end
end
